pipeline {
  agent any
  tools {
    maven 'M2_HOME' 
  }
  stages {
    stage('Cleanup') {
      steps {
        deleteDir()
      }
    }
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Build') {
      steps {
        sh 'mvn clean package'
      }
    }
    stage('Deploy') {
      steps {
        script {
          deploy adapters: [
            tomcat9(
              path: '', 
              url: 'http://localhost:8989/'
            )
          ], 
          contextPath: '/pipeline', 
          onFailure: false, 
          war: '**/target/*.war' 
        }
      }
    }
  }
}
